Args = --initialize-at-build-time=com.kabusair.nexuscleaner \
       --initialize-at-build-time=info.picocli \
       --initialize-at-build-time=org.objectweb.asm \
       --initialize-at-build-time=com.github.javaparser
